apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-and-mongodb
  template:
    metadata:
      labels:
        app: cart-and-mongodb
    spec:
      containers: 
      - name: cart-app
        image: yukc09/ecommer:latest
        ports:
        - containerPort: 3000 
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/shopping_cart"
        - name: PORT
          value: "3000"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "shopping_cart"